name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
    - uses: azure/container-actions/docker-login@master
      with: 
        username: ${{ secrets.username }} 
        password: ${{ secrets.password }} 
    - run: |
        cd kubectl
        docker build . -t clitools/kubectl
        docker push clitools/kubectl
